# Generated by Django 6.1.1 on 2026-09-19 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_modules', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_modules', to='modules.module', verbose_name='Módulo')),
                ('rol', models.CharField(choices=[('OWNER', 'Propietario'), ('MEMBER', 'Integrante')], default='MEMBER', max_length=20)),
            ],
            options={
                'verbose_name': 'Usuario por Módulo',
                'verbose_name_plural': 'Usuarios por Módulo',
                'db_table': 'user_module',
                'constraints': [models.UniqueConstraint(fields=('user', 'module'), name='unique_user_module')],
            },
        ),
    ]
