# Generated by Django 6.1.1 on 2026-09-22 02:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_usermodule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usermodule',
            constraint=models.UniqueConstraint(condition=models.Q(('rol', 'OWNER')), fields=('module',), name='unique_owner_per_module'),
        ),
    ]
